FORMAT: 1A
HOST: https://mt-trackr.herokuapp.com/

# Andela Maintenance Tracker

Maintenance Tracker App is an application that provides users with the ability to reach out to operations or repairs department regarding repair or maintenance requests and monitor the status of their request.

[Andela Maintenance Tracker API - Website](https://mt-trackr.herokuapp.com/)

[Send email to Andela Maintenance Tracker API](mailto:allanguwatudde@gmail.com)

## Authentication Collection [/]

### For new users to Signup [POST /auth/signup/]

+ Request (application/json)

        {
            "username":"some-username",
            "password":"iamsecret",
            "status":"normal"
        }

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"You were successfully signed up",
                "login":"http://127.0.0.1:5001/api/v1/login/"
            }
            
+ Response 403 (application/json)
    
    + Body 
    
            {
                "error":"Username already exists!"
            }
            
### For signed up users to Login [POST /auth/login/]

+ Request (application/json)

        {
            "username":"some-username",
            "password":"iamsecret"
        }

+ Response 200 (application/json)

    + Body
    
            {
                "username":"some-username",
                "token":"generatedtoken"
            }

+ Response 401 (application/json)

    + Body
    
            {
                "error":"Password and username didn't match"
            }
            
            
+ Response 403 (application/json)
    
    + Body 
    
            {
                "error":"Invalid format. no spaces"
            }
            
## Administrator Collection [//]

### For admin to get all requests made [GET /requests/]

+ Response 200 (application/json)

    + Body
    
            {
                "requests": [
                                {
                                    "created": "Wed, 20 Jun 2018 21:41:44 GMT",
                                    "department": "Stores",
                                    "detail": "We need to repair asap",
                                    "id": 1,
                                    "status": "pending",
                                    "title": "Elevator Maintenance",
                                    "user": "agmeteor"
                                }
                            ]
            }
    
+ Response 403 (application/json)
    
    + Body 
    
            {
                "error":"Access denied"
            }
            

### For admin to approve a particular request [PUT /requests/{requestId}/approve/]

+ Response 200 (application/json)

    + Body
    
            {
                
                "message":"Approved"
            }

### For admin to disapprove a particular request [PUT /requests/{requestId}/disapprove/]

+ Response 200 (application/json)

    + Body
    
            {
                
                "message":"Disapproved"
            }
            
### For admin to resolve a particular request [PUT /requests/{requestId}/resolve/]

+ Response 200 (application/json)

    + Body
    
            {
                
                "message":"Resolved"
            }
            
## Users Collection [///]

### For authenticated users to create a maintenance request [POST /api/v1/users/requests/]

+ Request (application/json)

        {
            
            "title": "Stairs Maintenance",
            "department": "Accounts",
            "detail": "We need to repair asap",
            "status":"pending"
        }

+ Response 201 (application/json)

    + Body
    
            {
                "created": "Tue, 19 Jun 2018 18:03:54 GMT",
                "department": "Stores",
                "detail": "We need to repair asap",
                "id": 1,
                "status": "pending",
                "title": "Elevator Maintenance",
                "user": "agmeteor"
            }
            
            
### For authenticated users to get all maintenance requests made by them [GET /api/v1/users/requests/]

+ Response 200 (application/json)

    + Body
    
            {
                "created": "Tue, 19 Jun 2018 18:03:54 GMT",
                "department": "Stores",
                "detail": "We need to repair asap",
                "id": 1,
                "status": "pending",
                "title": "Elevator Maintenance",
                "user": "agmeteor"
            }
            
### For authenticated users to get single maintenance request made by them [GET /api/v1/users/requests/{requestId}/]

+ Response 200 (application/json)

    + Body
    
            {
                "created": "Tue, 19 Jun 2018 18:03:54 GMT",
                "department": "Stores",
                "detail": "We need to repair asap",
                "id": 1,
                "status": "pending",
                "title": "Elevator Maintenance",
                "user": "agmeteor"
            }
            
### For authenticated users to edit a maintenance requests made by them [PUT /api/v1/users/requests/{requestId}/]

+ Request (application/json)

            {
                "department": "Stores",
                "detail": "We need to repair asap",
                "status": "pending",
                "title": "Elevator Maintenance"
            }
            
+ Response 201 (application/json)

    + Body
    
            {
                "department": "Stores",
                "detail": "We need to repair asap",
                "status": "pending",
                "title": "Elevator Maintenance"
            }