FORMAT: 1A
HOST: http://mt-trackr.herokuapp.com/

# Andela Maintenance Tracker

Maintenance Tracker App is an application that provides users with the ability to reach out to operations or repairs department regarding repair or maintenance requests and monitor the status of their request.

## Authentication Collection [/]

### For new users to Signup [POST /auth/signup/]

+ Request (application/json)

        {
            "username":"some-username",
            "password":"iamsecret",
            "status":"normal"
        }

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }
### For signed up to Login [POST /auth/login/]

+ Request (application/json)

        {
            "username":"some-username",
            "password":"iamsecret"
        }

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully logged in"
            }
            
## Administrator Collection [//]

### For admin to get all requests made [GET /requests/]

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }
            
### For admin to get a particular request [GET /requests/{requestId}/]

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }
            
### For admin to approve a particular request [PUT /requests/{requestId}/approve/]

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }

### For admin to disapprove a particular request [PUT /requests/{requestId}/disapprove/]

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }
            
### For admin to disapprove a particular request [PUT /requests/{requestId}/resolve/]

+ Response 201 (application/json)

    + Body
    
            {
                
                "message":"Successfully signed up"
            }